RMI-PACTA/r2dii.data

.gitignore, R/data_dictionary.R, _pkgdown.yml, man/data_dictionary.Rd
* Fix typo in documentation 
* Add link to my github page in pkgdown authors 
Closes #15
=> Release 0.0.2

README.Rmd, README.md
Closes 33
p.s. i made this issue, and pr all using command line tools!
`gh issue create`
`gh pr create`
:-)
=> Add grand total badge to README

data-raw/loanbook_demo.R
If it has a new column tests will fail, so no need to check here.
=> Remove needless code to create loanbook_demo

R/scenario_demo_2020.R, man/scenario_demo_2020.Rd
Forgot to document the new column under `@format`. This gives +1 to #63
=> Document new colum

.Rbuildignore, NEWS.md, README.md, cran-comments.md
This is a first pass through #91. We could address here what we see, merge into master, then prepare the CRAN release in a separate PR.
=> prepare release

NEWS.md, README.Rmd, README.md
https://www.tidyverse.org/lifecycle/#maturing
=> r2dii.data reached lifecycle-stage 'maturing'

data-raw/ald_demo.R, data-raw/region_isos.R, data-raw/region_isos_demo.R, data-raw/scenario_demo.R
I've added another region definition dictionary to the `region_isos` file, corresponding to the "Energy Technology Perspectives 2017" publication. 
Note: in the raw data sourcing file, there is some VERY WET work. I plan on working on this, but feel free to have a look right off the bat. Maybe we can do something similar to how we handle the classification files? 
Closes #109
=> add etp region isos (#109)

DESCRIPTION, NEWS.md
=> Depend on a version known to work

.github/workflows/R-CMD-check.yaml, R/utils.R
I recently updated the CI workflow and removed useful code by accident. This PR restore that code and cleans it up a bit.
=> Update and test data-raw/ on CI -- again

CRAN-RELEASE, DESCRIPTION, NEWS.md
r2dii.data v0.1.4 was just submitted to CRAN and is pending. I plan to follow up myself, but this PR should allow anyone to take over.
=> Submit 0.1.4

README.md, cran-comments.md, revdep/README.md, revdep/failures.md
This PR adds safe and minor changes in preparation for release (#179)
=> Prepare 0.1.5 for release

NEWS.md
Just reorganizing bullets in NEWS.
=> Prepare 0.1.6

.github/workflows/R-CMD-check.yaml
This is a low risk PR. It touches no user-facing code.
=> Use package here on CI

data-raw/classification_bridge.R
Follows #201 
This is a pretty safe PR that touches no production code -- only stuff in data-raw/. 
At most it could brake the CI pipeline but it wouldn't because #201 already installed
on CI what this PR needs.
=> Use here in data-raw/classification_bridge.R

data-raw/classification_bridge.R
Revert back to using `file.path()` so I can work from any rstudio project
into r2dii.data just by changing working directory.
=> In data-raw/ use not here but file.path

NEWS.md, README.md, revdep/README.md, revdep/cran.md, revdep/failures.md
=> prepare 0.1.8

README.md, revdep/README.md
=> Prepare 0.1.9

DESCRIPTION, NEWS.md, README.md, cran-comments.md, inst/WORDLIST, man/r2dii.data-package.Rd, man/scenario_demo_2020.Rd
- Polish NEWS.md
- Update README
- Update cran-comments.md
- Document
- Spellcheck
- Avoid R CMD check note about misspelling
- Redocument
=> Prepare 0.2.0

data-raw/ald_demo.R, data-raw/region_isos.R, man/region_isos.Rd, revdep/README.md, revdep/failures.md, tests/testthat/test-classification_bridge.R, tests/testthat/test-region_isos.R
Releates to #259 
- Update docs
- Style
- Update revdepcheck results
=> prepare 0.2.2

DESCRIPTION, NEWS.md
=> Submit to CRAN

_pkgdown.yml
This is a tiny change that touches no production code. It does have an impact on the public documentation, but if there is a problem it'd be catched in a similar review in r2dii.analysis. So I'll use reviewer's time for more userful stuff and go ahead and merge.
=> Update package list to include r2dii.plot

_pkgdown.yml
Same as https://github.com/2DegreesInvesting/r2dii.match/pull/382
=> Simpler News

DESCRIPTION, _pkgdown.yml, man/r2dii.data-package.Rd, man/region_isos.Rd
@maurolepore I also changed the order of authors in the `DESCRIPTION` and `pkgdown.yml` files. I wasn't sure if that was necessary, but it seemed to make sense. 
Closes #274
=> Maintainer changed from @maurolepore to @jdhoffa

DESCRIPTION
Prefer to use the same e-mail between github and CRAN
=> Update maintainer email

DESCRIPTION, NEWS.md, cran-comments.md
=> Prepare release 0.3.0

.github/workflows/render-rmarkdown.yaml
=> update render markdown action

DESCRIPTION, NEWS.md, cran-comments.md
CRAN Release for reverted demo data.
=> Version bump

.github/workflows/add-prs-and-issues-to-project.yml
See https://github.com/RMI-PACTA/r2dii.match/pull/441
=> Add issues and prs to r2dii suite GH project

tests/testthat/test-data_dictionary.R
=> Include all `demo` datasets in relevant test

DESCRIPTION, _pkgdown.yml
=> feat: use RMI `pkgdown` template

data-raw/abcd_demo.R, data-raw/classification_bridge.R, data-raw/loanbook_demo.R, data-raw/utils.R, man/sector_classifications.Rd, tests/testthat/test-classification_bridge.R, tests/testthat/test-loanbook_demo.R
This is a purely maintenance PR. 
- `styler::style_pkg()`
- `devtools::document()`
=> upkeep: style and document

NEWS.md
=> release: prepare `r2dii.data v0.5.0`

cran-comments.md
=> release: update `cran_comments.md`

DESCRIPTION, NEWS.md
=> release: Increment version number to 0.5.0

.github/workflows/R.yml
=> Add reverse dependency check

_pkgdown.yml
modernizing pkgdown config in line with:
- https://github.com/RMI-PACTA/r2dii.match/pull/499
- https://github.com/RMI-PACTA/r2dii.match/pull/500
- https://github.com/RMI-PACTA/r2dii.match/pull/502
=> Update pkdown config

_pkgdown.yml
- depends on [pacta.multi.loanbook](https://github.com/rmi-pacta/pacta.multi.loanbook) being released on CRAN
- towards https://github.com/RMI-PACTA/pacta.multi.loanbook/issues/148
=> add pacta.multi.loanbook to pkgs menu
